/* Generated by Yosys 0.66 (git sha1 7f8fdfd8d7bc08c749a2a969388d3425d4f369d5, x86_64-w64-mingw32-g++ 16.1.0 -march=nocona -msahf -mtune=generic -O2 -fstack-protector-strong -O3) */

module rng_mode_net(seed, q, feedback, visible);
  input [31:0] seed;
  wire [31:0] seed;
  input [31:0] q;
  wire [31:0] q;
  output [31:0] feedback;
  wire [31:0] feedback;
  output [31:0] visible;
  wire [31:0] visible;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire m_s27_q10;
  wire m_s28_q11;
  wire m_s29_q12;
  wire m_s30_q13;
  wire m_s31_q14;
  wire x_00000021;
  wire x_00000042;
  wire x_00000084;
  wire x_00000108;
  wire x_00000210;
  wire x_00000420;
  wire x_00000840;
  wire x_00001080;
  wire x_00002021;
  wire x_00002100;
  wire x_00004042;
  wire x_00004200;
  wire x_00008008;
  wire x_00008808;
  wire x_00010010;
  wire x_00011010;
  wire x_00420021;
  wire x_00840042;
  wire x_01080084;
  wire x_01088008;
  wire x_02100108;
  wire x_02110010;
  wire x_04200021;
  wire x_04200210;
  wire x_08008400;
  wire x_08008840;
  wire x_08400042;
  wire x_08400420;
  wire x_10010800;
  wire x_10011080;
  wire x_10800084;
  wire x_10800840;
  wire x_20001001;
  wire x_20002101;
  wire x_21000108;
  wire x_21001080;
  wire x_40002002;
  wire x_40004202;
  wire x_40420002;
  wire x_42000210;
  wire x_42002100;
  wire x_80000404;
  wire x_80004004;
  wire x_80840004;
  wire x_84000420;
  wire x_84004200;
  NOR _057_ (
    .A(q[14]),
    .B(seed[26]),
    .Y(_000_)
  );
  XNOR _058_ (
    .A(q[9]),
    .B(_000_),
    .Y(feedback[26])
  );
  NOR _059_ (
    .A(seed[26]),
    .B(q[26]),
    .Y(_001_)
  );
  NOR _060_ (
    .A(q[31]),
    .B(seed[9]),
    .Y(_002_)
  );
  XNOR _061_ (
    .A(_001_),
    .B(_002_),
    .Y(_003_)
  );
  XNOR _062_ (
    .A(feedback[26]),
    .B(_003_),
    .Y(visible[9])
  );
  NOR _063_ (
    .A(q[10]),
    .B(seed[22]),
    .Y(_004_)
  );
  XNOR _064_ (
    .A(q[5]),
    .B(_004_),
    .Y(feedback[22])
  );
  XNOR _065_ (
    .A(_003_),
    .B(feedback[22]),
    .Y(feedback[9])
  );
  OR _066_ (
    .A(seed[31]),
    .B(q[2]),
    .Y(_005_)
  );
  NOR _067_ (
    .A(seed[14]),
    .B(q[31]),
    .Y(_006_)
  );
  XNOR _068_ (
    .A(_005_),
    .B(_006_),
    .Y(_007_)
  );
  NOR _069_ (
    .A(seed[18]),
    .B(q[18]),
    .Y(_008_)
  );
  NOR _070_ (
    .A(q[23]),
    .B(seed[1]),
    .Y(_009_)
  );
  XNOR _071_ (
    .A(_008_),
    .B(_009_),
    .Y(_010_)
  );
  XNOR _072_ (
    .A(_007_),
    .B(_010_),
    .Y(feedback[1])
  );
  XOR _073_ (
    .A(q[14]),
    .B(_007_),
    .Y(visible[14])
  );
  OR _074_ (
    .A(q[10]),
    .B(seed[27]),
    .Y(feedback[27])
  );
  XOR _075_ (
    .A(_007_),
    .B(feedback[27]),
    .Y(feedback[14])
  );
  NOR _076_ (
    .A(q[13]),
    .B(seed[25]),
    .Y(_011_)
  );
  XNOR _077_ (
    .A(q[8]),
    .B(_011_),
    .Y(feedback[25])
  );
  NOR _078_ (
    .A(seed[25]),
    .B(q[25]),
    .Y(_012_)
  );
  NOR _079_ (
    .A(q[30]),
    .B(seed[8]),
    .Y(_013_)
  );
  XNOR _080_ (
    .A(_012_),
    .B(_013_),
    .Y(_014_)
  );
  XNOR _081_ (
    .A(feedback[25]),
    .B(_014_),
    .Y(visible[8])
  );
  NOR _082_ (
    .A(q[4]),
    .B(seed[21]),
    .Y(_015_)
  );
  XNOR _083_ (
    .A(q[9]),
    .B(_015_),
    .Y(feedback[21])
  );
  XNOR _084_ (
    .A(_014_),
    .B(feedback[21]),
    .Y(feedback[8])
  );
  NOR _085_ (
    .A(seed[30]),
    .B(q[1]),
    .Y(_016_)
  );
  NOR _086_ (
    .A(seed[13]),
    .B(q[30]),
    .Y(_017_)
  );
  XNOR _087_ (
    .A(_016_),
    .B(_017_),
    .Y(_018_)
  );
  NOR _088_ (
    .A(seed[17]),
    .B(q[17]),
    .Y(_019_)
  );
  NOR _089_ (
    .A(q[22]),
    .B(seed[0]),
    .Y(_020_)
  );
  XNOR _090_ (
    .A(_019_),
    .B(_020_),
    .Y(_021_)
  );
  XOR _091_ (
    .A(_018_),
    .B(_021_),
    .Y(feedback[0])
  );
  XNOR _092_ (
    .A(feedback[26]),
    .B(_018_),
    .Y(feedback[13])
  );
  XNOR _093_ (
    .A(q[13]),
    .B(_018_),
    .Y(visible[13])
  );
  NOR _094_ (
    .A(q[12]),
    .B(seed[24]),
    .Y(_022_)
  );
  XNOR _095_ (
    .A(q[7]),
    .B(_022_),
    .Y(feedback[24])
  );
  NOR _096_ (
    .A(seed[24]),
    .B(q[24]),
    .Y(_023_)
  );
  NOR _097_ (
    .A(q[29]),
    .B(seed[7]),
    .Y(_024_)
  );
  XNOR _098_ (
    .A(_023_),
    .B(_024_),
    .Y(_025_)
  );
  XNOR _099_ (
    .A(feedback[24]),
    .B(_025_),
    .Y(visible[7])
  );
  NOR _100_ (
    .A(q[3]),
    .B(seed[20]),
    .Y(_026_)
  );
  XNOR _101_ (
    .A(q[8]),
    .B(_026_),
    .Y(feedback[20])
  );
  XNOR _102_ (
    .A(_025_),
    .B(feedback[20]),
    .Y(feedback[7])
  );
  NOR _103_ (
    .A(seed[29]),
    .B(q[0]),
    .Y(_027_)
  );
  NOR _104_ (
    .A(seed[12]),
    .B(q[29]),
    .Y(_028_)
  );
  XNOR _105_ (
    .A(_027_),
    .B(_028_),
    .Y(_029_)
  );
  XNOR _106_ (
    .A(feedback[25]),
    .B(_029_),
    .Y(feedback[12])
  );
  XNOR _107_ (
    .A(q[12]),
    .B(_029_),
    .Y(visible[12])
  );
  NOR _108_ (
    .A(q[6]),
    .B(seed[23]),
    .Y(_030_)
  );
  XNOR _109_ (
    .A(q[11]),
    .B(_030_),
    .Y(feedback[23])
  );
  NOR _110_ (
    .A(seed[23]),
    .B(q[23]),
    .Y(_031_)
  );
  NOR _111_ (
    .A(q[28]),
    .B(seed[6]),
    .Y(_032_)
  );
  XNOR _112_ (
    .A(_031_),
    .B(_032_),
    .Y(_033_)
  );
  XNOR _113_ (
    .A(feedback[23]),
    .B(_033_),
    .Y(visible[6])
  );
  NOR _114_ (
    .A(q[2]),
    .B(seed[19]),
    .Y(_034_)
  );
  XNOR _115_ (
    .A(q[7]),
    .B(_034_),
    .Y(feedback[19])
  );
  XNOR _116_ (
    .A(_033_),
    .B(feedback[19]),
    .Y(feedback[6])
  );
  NOR _117_ (
    .A(seed[28]),
    .B(q[16]),
    .Y(_035_)
  );
  NOR _118_ (
    .A(seed[11]),
    .B(q[28]),
    .Y(_036_)
  );
  XNOR _119_ (
    .A(_035_),
    .B(_036_),
    .Y(_037_)
  );
  XNOR _120_ (
    .A(feedback[24]),
    .B(_037_),
    .Y(feedback[11])
  );
  XNOR _121_ (
    .A(q[11]),
    .B(_037_),
    .Y(visible[11])
  );
  NOR _122_ (
    .A(seed[22]),
    .B(q[22]),
    .Y(_038_)
  );
  NOR _123_ (
    .A(q[27]),
    .B(seed[5]),
    .Y(_039_)
  );
  XNOR _124_ (
    .A(_038_),
    .B(_039_),
    .Y(_040_)
  );
  XNOR _125_ (
    .A(feedback[22]),
    .B(_040_),
    .Y(visible[5])
  );
  NOR _126_ (
    .A(q[1]),
    .B(seed[18]),
    .Y(_041_)
  );
  XNOR _127_ (
    .A(q[6]),
    .B(_041_),
    .Y(visible[18])
  );
  XNOR _128_ (
    .A(_040_),
    .B(visible[18]),
    .Y(feedback[5])
  );
  NOR _129_ (
    .A(seed[27]),
    .B(q[15]),
    .Y(_042_)
  );
  NOR _130_ (
    .A(seed[10]),
    .B(q[27]),
    .Y(_043_)
  );
  XNOR _131_ (
    .A(_042_),
    .B(_043_),
    .Y(_044_)
  );
  XNOR _132_ (
    .A(feedback[23]),
    .B(_044_),
    .Y(feedback[10])
  );
  XNOR _133_ (
    .A(q[10]),
    .B(_044_),
    .Y(visible[10])
  );
  NOR _134_ (
    .A(seed[21]),
    .B(q[21]),
    .Y(_045_)
  );
  NOR _135_ (
    .A(q[26]),
    .B(seed[4]),
    .Y(_046_)
  );
  XNOR _136_ (
    .A(_045_),
    .B(_046_),
    .Y(_047_)
  );
  XNOR _137_ (
    .A(feedback[21]),
    .B(_047_),
    .Y(visible[4])
  );
  NOR _138_ (
    .A(q[0]),
    .B(seed[17]),
    .Y(_048_)
  );
  XNOR _139_ (
    .A(q[5]),
    .B(_048_),
    .Y(visible[17])
  );
  XNOR _140_ (
    .A(_047_),
    .B(visible[17]),
    .Y(feedback[4])
  );
  NOR _141_ (
    .A(q[16]),
    .B(seed[16]),
    .Y(_049_)
  );
  XNOR _142_ (
    .A(q[4]),
    .B(_049_),
    .Y(visible[16])
  );
  NOR _143_ (
    .A(seed[20]),
    .B(q[20]),
    .Y(_050_)
  );
  NOR _144_ (
    .A(q[25]),
    .B(seed[3]),
    .Y(_051_)
  );
  XNOR _145_ (
    .A(_050_),
    .B(_051_),
    .Y(_052_)
  );
  XNOR _146_ (
    .A(visible[16]),
    .B(_052_),
    .Y(feedback[3])
  );
  XNOR _147_ (
    .A(feedback[20]),
    .B(_052_),
    .Y(visible[3])
  );
  NOR _148_ (
    .A(q[15]),
    .B(seed[15]),
    .Y(_053_)
  );
  XNOR _149_ (
    .A(q[3]),
    .B(_053_),
    .Y(visible[15])
  );
  NOR _150_ (
    .A(seed[19]),
    .B(q[19]),
    .Y(_054_)
  );
  NOR _151_ (
    .A(q[24]),
    .B(seed[2]),
    .Y(_055_)
  );
  XNOR _152_ (
    .A(_054_),
    .B(_055_),
    .Y(_056_)
  );
  XNOR _153_ (
    .A(visible[15]),
    .B(_056_),
    .Y(feedback[2])
  );
  XNOR _154_ (
    .A(feedback[19]),
    .B(_056_),
    .Y(visible[2])
  );
  XNOR _155_ (
    .A(_010_),
    .B(visible[18]),
    .Y(visible[1])
  );
  XNOR _156_ (
    .A(_021_),
    .B(visible[17]),
    .Y(visible[0])
  );
  OR _157_ (
    .A(q[12]),
    .B(seed[29]),
    .Y(feedback[29])
  );
  XOR _158_ (
    .A(visible[16]),
    .B(feedback[29]),
    .Y(feedback[16])
  );
  OR _159_ (
    .A(q[11]),
    .B(seed[28]),
    .Y(feedback[28])
  );
  XOR _160_ (
    .A(visible[15]),
    .B(feedback[28]),
    .Y(feedback[15])
  );
  OR _161_ (
    .A(q[14]),
    .B(seed[31]),
    .Y(feedback[31])
  );
  XOR _162_ (
    .A(visible[18]),
    .B(feedback[31]),
    .Y(feedback[18])
  );
  OR _163_ (
    .A(q[13]),
    .B(seed[30]),
    .Y(feedback[30])
  );
  XOR _164_ (
    .A(visible[17]),
    .B(feedback[30]),
    .Y(feedback[17])
  );
  assign x_84004200 = visible[9];
  assign x_84000420 = feedback[9];
  assign x_80840004 = feedback[1];
  assign x_80004004 = visible[14];
  assign x_80000404 = feedback[14];
  assign x_42002100 = visible[8];
  assign x_42000210 = feedback[8];
  assign x_40420002 = feedback[0];
  assign x_40004202 = feedback[13];
  assign x_40002002 = visible[13];
  assign x_21001080 = visible[7];
  assign x_21000108 = feedback[7];
  assign x_20002101 = feedback[12];
  assign x_20001001 = visible[12];
  assign x_10800840 = visible[6];
  assign x_10800084 = feedback[6];
  assign x_10011080 = feedback[11];
  assign x_10010800 = visible[11];
  assign x_08400420 = visible[5];
  assign x_08400042 = feedback[5];
  assign x_08008840 = feedback[10];
  assign x_08008400 = visible[10];
  assign x_04200210 = visible[4];
  assign x_04200021 = feedback[4];
  assign x_02110010 = feedback[3];
  assign x_02100108 = visible[3];
  assign x_01088008 = feedback[2];
  assign x_01080084 = visible[2];
  assign x_00840042 = visible[1];
  assign x_00420021 = visible[0];
  assign x_00011010 = feedback[16];
  assign x_00008808 = feedback[15];
  assign x_00004042 = feedback[18];
  assign x_00002021 = feedback[17];
  assign x_00010010 = visible[16];
  assign x_00008008 = visible[15];
  assign x_00004200 = feedback[26];
  assign x_00002100 = feedback[25];
  assign x_00001080 = feedback[24];
  assign x_00000840 = feedback[23];
  assign x_00000420 = feedback[22];
  assign x_00000210 = feedback[21];
  assign x_00000108 = feedback[20];
  assign x_00000084 = feedback[19];
  assign x_00000042 = visible[18];
  assign x_00000021 = visible[17];
  assign m_s31_q14 = feedback[31];
  assign m_s30_q13 = feedback[30];
  assign m_s29_q12 = feedback[29];
  assign m_s28_q11 = feedback[28];
  assign m_s27_q10 = feedback[27];
  assign visible[31:19] = { q[14:10], feedback[26:19] };
endmodule
