"""Strict TOML project configuration."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import tomllib


@dataclass(frozen=True)
class PortBinding:
    component_label: str
    pin: str


@dataclass(frozen=True)
class ProjectConfig:
    manifest: Path
    name: str
    top: str
    sources: tuple[Path, ...]
    target_kind: str
    logical_key: str
    description: str
    template: Path | None
    port_bindings: dict[str, PortBinding]
    pack_widths: tuple[int, ...]
    horizontal_clearance: int
    vertical_clearance: int


def _nonempty(value: object, field: str) -> str:
    text = str(value).strip()
    if not text:
        raise ValueError(f"{field} cannot be empty")
    return text


def load_project(path: Path) -> ProjectConfig:
    manifest = Path(path).resolve()
    raw = tomllib.loads(manifest.read_text(encoding="utf-8"))
    project = raw.get("project")
    target = raw.get("target")
    if not isinstance(project, dict) or not isinstance(target, dict):
        raise ValueError("project.toml requires [project] and [target]")
    base = manifest.parent
    sources_raw = project.get("sources")
    if not isinstance(sources_raw, list) or not sources_raw:
        raise ValueError("[project].sources must be a non-empty array")
    sources = tuple((base / _nonempty(item, "project.sources")).resolve() for item in sources_raw)
    missing = [str(source) for source in sources if not source.is_file()]
    if missing:
        raise FileNotFoundError(f"Verilog source files are missing: {missing!r}")
    target_kind = _nonempty(target.get("kind", "foundry"), "target.kind")
    if target_kind not in {"foundry", "level"}:
        raise ValueError("target.kind must be 'foundry' or 'level'")
    template_raw = target.get("template")
    template = (base / str(template_raw)).resolve() if template_raw else None
    if target_kind == "level" and (template is None or not template.is_file()):
        raise ValueError("level target requires an existing target.template v15 file")
    bindings_raw = target.get("ports", {})
    if not isinstance(bindings_raw, dict):
        raise ValueError("target.ports must be a TOML table")
    bindings: dict[str, PortBinding] = {}
    for port_name, binding in bindings_raw.items():
        if not isinstance(binding, dict):
            raise ValueError(f"target.ports.{port_name} must be a table")
        bindings[str(port_name)] = PortBinding(
            component_label=_nonempty(binding.get("component_label"), "component_label"),
            pin=_nonempty(binding.get("pin", "value"), "pin"),
        )
    compile_raw = raw.get("compile", {})
    layout_raw = raw.get("layout", {})
    pack_widths = tuple(int(value) for value in compile_raw.get("pack_widths", [8, 4, 2]))
    if not pack_widths or any(value not in {2, 4, 8} for value in pack_widths):
        raise ValueError("compile.pack_widths may contain only 2, 4, and 8")
    if tuple(sorted(set(pack_widths), reverse=True)) != pack_widths:
        raise ValueError("compile.pack_widths must be unique and descending")
    return ProjectConfig(
        manifest=manifest,
        name=_nonempty(project.get("name", project.get("top")), "project.name"),
        top=_nonempty(project.get("top"), "project.top"),
        sources=sources,
        target_kind=target_kind,
        logical_key=_nonempty(
            target.get("logical_key", f"foundry/codex/verilog/{project.get('top', '')}"),
            "target.logical_key",
        ),
        description=str(target.get("description", "Generated by turingsynth")).strip(),
        template=template,
        port_bindings=bindings,
        pack_widths=pack_widths,
        # Four empty columns are the orthogonal-routing minimum: two for a
        # protected driver lead, one shared turn/track column, and one for the
        # consumer lead. Clearance measures the bounds-to-bounds distance.
        horizontal_clearance=max(5, int(layout_raw.get("horizontal_clearance", 5))),
        vertical_clearance=max(3, int(layout_raw.get("vertical_clearance", 3))),
    )
