"""Materialize and deploy the reviewed 84/7/588 Byte Adder DAG.

The source DAG is generated by ``byte_adder_root/build_hybrid_phasefold_84_d7.py``.
This script performs a second, physical reconstruction using only current v15
campaign ports and legal primitive components.  It then proves node-by-node
packed semantics, tri-state network ownership, recursive delay, current sprite
geometry, and v15 round-trip identity before directly replacing the reviewed
candidate and live ``byte_adder/Default`` file.  No backup is created.
"""

from __future__ import annotations

from collections import Counter, defaultdict
from dataclasses import replace
from hashlib import sha256
import importlib.util
import json
from pathlib import Path
import sys
from typing import Any

from tc_save_lab.codec import decode_v15, encode_v15
from tc_save_lab.foundry import _assert_game_not_running
from tc_save_lab.model import Circuit, Component, Point
from tc_save_lab.pins import I, O, T, analyze_connectivity, positioned_pins
from tc_save_lab.sprite_geometry import DEFAULT_COMPONENT_SPRITE_ROOT, audit_sprite_geometry
from tc_save_lab.builder import stable_permanent_id

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

import hub79_bootstrap as physical
from route_byte_adder import Connection


ROOT = HERE.parents[1]
DAG_SOURCE = ROOT / ".research" / "byte_adder_root" / "byte-adder-hybrid-phasefold-g84-d7.json"
DAG_BUILDER = ROOT / ".research" / "byte_adder_root" / "build_hybrid_phasefold_84_d7.py"
MACRO_CERTIFICATE = ROOT / ".research" / "byte_adder_root" / "full1z-s4-c2-g10-n8.json"
OUT_DIR = Path(__file__).with_name("hybrid84_phasefold")
OUT_PROXY = OUT_DIR / "semantic_proxy.circuit.data"
OUT_CERTIFICATE = OUT_DIR / "machine_certificate.json"
REPOSITORY_CANDIDATE = ROOT / "examples" / "byte_adder" / "candidate" / "circuit.data"
FORMAL_SAVE = (
    Path.home()
    / "AppData"
    / "Roaming"
    / "Turing Complete"
    / "schematics"
    / "byte_adder"
    / "Default"
    / "circuit.data"
)

ASSIGNMENTS = 1 << 17
ALL = (1 << ASSIGNMENTS) - 1
EXPECTED_SCORE = {"gate": 84, "delay": 7, "energy": 588}
OP_KIND = {"AND": 4, "NAND": 6, "OR": 7, "NOR": 9}
OP_COST = {"AND": 1, "NAND": 1, "OR": 1, "NOR": 1, "BUS": 4}


def _load_module(path: Path, name: str):
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load Python module {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def _review_dag() -> tuple[dict[str, Any], dict[int, dict[str, Any]], dict[str, Any]]:
    persisted = json.loads(DAG_SOURCE.read_text(encoding="utf-8"))
    generated = _load_module(DAG_BUILDER, "byte_adder_hybrid84_review").build()
    if generated != persisted:
        raise RuntimeError("persisted 84/7 DAG differs from its current generator")

    metrics = persisted["metrics"]
    if {key: metrics[key] for key in EXPECTED_SCORE} != EXPECTED_SCORE:
        raise RuntimeError(f"unexpected reviewed score: {metrics!r}")
    semantic = persisted["semantic"]
    if semantic["truth_table_rows"] != ASSIGNMENTS:
        raise RuntimeError("reviewed DAG does not cover the complete 17-input domain")
    if (
        semantic["mismatch_union_count"]
        or semantic["conflict_assignment_count"]
        or any(semantic["z_assignment_count_by_output"])
    ):
        raise RuntimeError(f"reviewed DAG semantic certificate is not clean: {semantic!r}")

    factory_dag = persisted["factory_dag"]
    nodes = factory_dag["nodes"]
    by_id = {int(node["id"]): node for node in nodes}
    if len(by_id) != len(nodes):
        raise RuntimeError("duplicate node id in reviewed DAG")
    if len(nodes) != metrics["reachable_nodes"]:
        raise RuntimeError("reachable node count differs from serialized DAG")
    expected_inputs = {
        *{f"a{bit}" for bit in range(8)},
        *{f"b{bit}" for bit in range(8)},
        "cin",
    }
    actual_inputs = {node["label"] for node in nodes if node["op"] == "INPUT"}
    if actual_inputs != expected_inputs:
        raise RuntimeError(
            f"input labels changed: missing={expected_inputs-actual_inputs!r}, "
            f"extra={actual_inputs-expected_inputs!r}"
        )

    arrivals: dict[int, int] = {}
    reviewed_cost = 0
    bus_ids = []
    for node in nodes:
        node_id = int(node["id"])
        op = node["op"]
        args = tuple(int(value) for value in node["args"])
        if any(arg not in arrivals for arg in args):
            raise RuntimeError(f"node {node_id} is not topologically serialized: {args!r}")
        if op in {"CONST", "INPUT"}:
            expected_cost = 0
            expected_step = 0
            expected_arrival = 0
        elif op in OP_KIND:
            if len(args) != 2:
                raise RuntimeError(f"ordinary gate {node_id} is not binary")
            expected_cost = OP_COST[op]
            expected_step = 1
            expected_arrival = max(arrivals[arg] for arg in args) + 1
        elif op == "BUS":
            if len(args) != 4 or len(args) % 2:
                raise RuntimeError(f"BUS {node_id} does not own exactly two drivers")
            expected_cost = OP_COST[op]
            expected_step = 1
            expected_arrival = max(arrivals[arg] for arg in args) + 1
            bus_ids.append(node_id)
            if node.get("resolved_network") != f"bus_node_{node_id}":
                raise RuntimeError(f"BUS {node_id} lost its resolved-network owner")
            owners = {driver["owner"] for driver in node.get("drivers", ())}
            if owners != {f"bus_node_{node_id}"}:
                raise RuntimeError(f"BUS {node_id} driver ownership is not exclusive")
        else:
            raise RuntimeError(f"unsupported reviewed operation {op!r}")
        if (
            node["cost"] != expected_cost
            or node["step_delay"] != expected_step
            or node["arrival"] != expected_arrival
        ):
            raise RuntimeError(f"node {node_id} cost/delay annotation changed: {node!r}")
        if bool(node["may_z"]) != (op == "BUS"):
            raise RuntimeError(f"node {node_id} has inconsistent may_z annotation")
        arrivals[node_id] = expected_arrival
        reviewed_cost += expected_cost

    outputs = tuple(int(value) for value in factory_dag["outputs"])
    if len(outputs) != 9 or any(output not in by_id for output in outputs):
        raise RuntimeError(f"invalid reviewed outputs: {outputs!r}")
    output_arrivals = [arrivals[output] for output in outputs]
    if output_arrivals != metrics["output_arrivals"]:
        raise RuntimeError("output arrival vector differs from recursive node audit")
    if reviewed_cost != EXPECTED_SCORE["gate"] or max(output_arrivals) != EXPECTED_SCORE["delay"]:
        raise RuntimeError("reviewed recursive score does not equal 84/7")
    if len(bus_ids) != 6:
        raise RuntimeError(f"reviewed BUS population changed: {bus_ids!r}")

    dag_hash_payload = {
        "outputs": list(outputs),
        "nodes": nodes,
        "live_node_count": factory_dag["live_node_count"],
    }
    dag_hash = sha256(
        json.dumps(dag_hash_payload, ensure_ascii=True, separators=(",", ":")).encode()
    ).hexdigest()
    if dag_hash != factory_dag["sha256"]:
        raise RuntimeError("serialized factory DAG hash mismatch")

    macro_hash = sha256(MACRO_CERTIFICATE.read_bytes()).hexdigest()
    if macro_hash != persisted["bit0_joint_macro"]["certificate_sha256"]:
        raise RuntimeError("bit-0 joint macro certificate hash mismatch")
    source_review = {
        "dag_source": str(DAG_SOURCE.relative_to(ROOT)).replace("\\", "/"),
        "dag_source_sha256": sha256(DAG_SOURCE.read_bytes()).hexdigest(),
        "dag_builder": str(DAG_BUILDER.relative_to(ROOT)).replace("\\", "/"),
        "dag_builder_sha256": sha256(DAG_BUILDER.read_bytes()).hexdigest(),
        "factory_dag_sha256": dag_hash,
        "structural_sha256": metrics["structural_sha256"],
        "macro_certificate": str(MACRO_CERTIFICATE.relative_to(ROOT)).replace("\\", "/"),
        "macro_certificate_sha256": macro_hash,
        "generator_replay_equal": True,
        "recursive_cost_delay_verified": True,
    }
    return persisted, by_id, source_review


def _variable(index: int) -> int:
    if index < 3:
        return int.from_bytes(bytes([(0xAA, 0xCC, 0xF0)[index]]) * (ASSIGNMENTS // 8), "little")
    block = 1 << (index - 3)
    data = (bytes(block) + bytes([0xFF]) * block) * (ASSIGNMENTS // (16 * block))
    return int.from_bytes(data, "little")


def _logical_states(nodes: tuple[dict[str, Any], ...]) -> dict[int, dict[str, int]]:
    variables = {
        **{f"a{bit}": _variable(bit) for bit in range(8)},
        **{f"b{bit}": _variable(8 + bit) for bit in range(8)},
        "cin": _variable(16),
    }
    states: dict[int, dict[str, int]] = {}
    for node in nodes:
        node_id = int(node["id"])
        op = node["op"]
        args = [states[int(value)] for value in node["args"]]
        if op == "CONST":
            if node["label"] != "1":
                raise RuntimeError("only the reviewed constant-one source is supported")
            state = {"bits": ALL, "driven": ALL, "conflict": 0, "depth": 0}
        elif op == "INPUT":
            state = {
                "bits": variables[node["label"]],
                "driven": ALL,
                "conflict": 0,
                "depth": 0,
            }
        elif op in OP_KIND:
            if any(value["conflict"] for value in args):
                raise RuntimeError(f"ordinary node {node_id} consumes a conflicting BUS")
            left, right = args[0]["bits"], args[1]["bits"]
            if op == "AND":
                bits = left & right
            elif op == "NAND":
                bits = ~(left & right) & ALL
            elif op == "OR":
                bits = left | right
            elif op == "NOR":
                bits = ~(left | right) & ALL
            else:
                raise AssertionError(op)
            state = {
                "bits": bits,
                "driven": ALL,
                "conflict": 0,
                "depth": max(value["depth"] for value in args) + 1,
            }
        elif op == "BUS":
            ones = 0
            zeros = 0
            driven = 0
            conflict = 0
            for offset in range(0, len(args), 2):
                enable, data = args[offset], args[offset + 1]
                driver_enable = enable["bits"]
                driver_ones = driver_enable & data["bits"]
                ones |= driver_ones
                zeros |= driver_enable & (~data["bits"] & ALL)
                driven |= driver_enable
                conflict |= enable["conflict"] | data["conflict"]
            conflict |= ones & zeros
            state = {
                "bits": ones,
                "driven": driven,
                "conflict": conflict,
                "depth": max(value["depth"] for value in args) + 1,
            }
        else:
            raise AssertionError(op)
        if state["depth"] != node["arrival"]:
            raise RuntimeError(f"packed replay depth mismatch at node {node_id}")
        states[node_id] = state
    return states


def _component_pin(components: tuple[Component, ...], index: int, name: str) -> Point:
    values = [
        pin.position
        for pin in positioned_pins(components[index], index)
        if pin.name == name
    ]
    if len(values) != 1:
        raise RuntimeError(f"component {index} lacks exactly one pin {name!r}")
    return values[0]


def _build_physical(
    payload: dict[str, Any],
    by_id: dict[int, dict[str, Any]],
) -> tuple[Circuit, tuple[Connection, ...], dict[str, Any]]:
    identity = "byte_adder:hybrid-phasefold-g84-d7"
    immutable = physical._scaffold()
    label_index = {component.user_label: index for index, component in enumerate(immutable)}
    mutables: list[Component] = []

    def append(component: Component) -> int:
        index = len(immutable) + len(mutables)
        mutables.append(component)
        return index

    a_split = append(
        Component(17, (0, 0), 0, stable_permanent_id(identity, "a-split"), word_size=8)
    )
    b_split = append(
        Component(17, (0, 0), 0, stable_permanent_id(identity, "b-split"), word_size=8)
    )
    node_components: dict[int, int] = {}
    bus_switches: dict[int, tuple[int, int]] = {}
    for node in payload["factory_dag"]["nodes"]:
        node_id = int(node["id"])
        op = node["op"]
        if op == "CONST":
            node_components[node_id] = append(
                Component(2, (0, 0), 0, stable_permanent_id(identity, f"const-{node_id}"))
            )
        elif op in OP_KIND:
            node_components[node_id] = append(
                Component(
                    OP_KIND[op],
                    (0, 0),
                    0,
                    stable_permanent_id(identity, f"node-{node_id}-{op.lower()}"),
                )
            )
        elif op == "BUS":
            switches = tuple(
                append(
                    Component(
                        12,
                        (0, 0),
                        0,
                        stable_permanent_id(identity, f"bus-{node_id}-driver-{driver}"),
                    )
                )
                for driver in range(2)
            )
            bus_switches[node_id] = (switches[0], switches[1])
    merger = append(
        Component(16, (0, 0), 0, stable_permanent_id(identity, "sum-merger"), word_size=8)
    )

    rows = tuple(
        index * 12 - ((len(mutables) - 1) * 12) // 2
        for index in range(len(mutables))
    )
    placed_mutables = tuple(
        replace(component, position=(48 + slot * 40, rows[slot]))
        for slot, component in enumerate(mutables)
    )
    components = tuple([*immutable, *placed_mutables])
    if len({component.permanent_id for component in components}) != len(components):
        raise RuntimeError("physical candidate has duplicate permanent IDs")

    network_members: dict[str, list[Point]] = defaultdict(list)
    node_pin_refs: dict[int, tuple[int, str]] = {}
    input_nodes = {
        node["label"]: int(node["id"])
        for node in payload["factory_dag"]["nodes"]
        if node["op"] == "INPUT"
    }
    for bit in range(8):
        node_pin_refs[input_nodes[f"a{bit}"]] = (a_split, f"out{bit}")
        node_pin_refs[input_nodes[f"b{bit}"]] = (b_split, f"out{bit}")
    node_pin_refs[input_nodes["cin"]] = (label_index["Carry in"], "value")
    for node_id, component_index in node_components.items():
        node_pin_refs[node_id] = (component_index, "out")
    for node_id, switches in bus_switches.items():
        node_pin_refs[node_id] = (switches[0], "out")

    def add_member(label: str, point: Point) -> None:
        if point not in network_members[label]:
            network_members[label].append(point)

    def add_node_member(node_id: int, point: Point) -> None:
        add_member(f"signal:{node_id}", point)

    add_member(
        "bridge:A",
        _component_pin(components, label_index["A"], "value"),
    )
    add_member("bridge:A", _component_pin(components, a_split, "in"))
    add_member(
        "bridge:B",
        _component_pin(components, label_index["B"], "value"),
    )
    add_member("bridge:B", _component_pin(components, b_split, "in"))
    add_member("bridge:Output", _component_pin(components, merger, "out"))
    add_member(
        "bridge:Output",
        _component_pin(components, label_index["Output"], "value"),
    )

    for node_id, node in by_id.items():
        if node["op"] == "BUS":
            for switch in bus_switches[node_id]:
                add_node_member(node_id, _component_pin(components, switch, "out"))
        else:
            source_index, source_name = node_pin_refs[node_id]
            add_node_member(node_id, _component_pin(components, source_index, source_name))

    for node_id, node in by_id.items():
        op = node["op"]
        args = tuple(int(value) for value in node["args"])
        if op in OP_KIND:
            component_index = node_components[node_id]
            for input_index, argument in enumerate(args):
                add_node_member(
                    argument,
                    _component_pin(components, component_index, f"in{input_index}"),
                )
        elif op == "BUS":
            switches = bus_switches[node_id]
            for driver, switch in enumerate(switches):
                enable = args[driver * 2]
                data = args[driver * 2 + 1]
                add_node_member(enable, _component_pin(components, switch, "enable"))
                add_node_member(data, _component_pin(components, switch, "in"))

    outputs = tuple(int(value) for value in payload["factory_dag"]["outputs"])
    for bit, node_id in enumerate(outputs[:8]):
        add_node_member(node_id, _component_pin(components, merger, f"in{bit}"))
    add_node_member(
        outputs[8],
        _component_pin(components, label_index["Carry out"], "value"),
    )

    point_owner: dict[Point, str] = {}
    connections: list[Connection] = []
    for label, points in sorted(network_members.items()):
        if len(points) < 2:
            raise RuntimeError(f"physical network {label!r} has no receiver")
        for point in points:
            previous = point_owner.get(point)
            if previous is not None and previous != label:
                raise RuntimeError(
                    f"pin point {point!r} belongs to both {previous!r} and {label!r}"
                )
            point_owner[point] = label
        anchor = points[0]
        connections.extend(
            Connection(label, anchor, point)
            for point in points[1:]
        )

    wires = physical._channel_route(components, tuple(connections))
    baseline = decode_v15(
        (ROOT / "examples" / "byte_adder" / "baseline" / "circuit.data").read_bytes()
    )
    candidate = replace(
        baseline,
        custom_id=0,
        hub_id=0,
        design=b"",
        gate=EXPECTED_SCORE["gate"],
        delay=EXPECTED_SCORE["delay"],
        description="Codex 84/7 Q-phase Switch byte adder",
        components=components,
        wires=wires,
    )
    mapping = {
        "label_index": label_index,
        "a_split": a_split,
        "b_split": b_split,
        "merger": merger,
        "node_components": node_components,
        "bus_switches": bus_switches,
        "node_pin_refs": node_pin_refs,
    }
    return candidate, tuple(connections), mapping


def _audit_candidate(
    candidate: Circuit,
    connections: tuple[Connection, ...],
    payload: dict[str, Any],
    by_id: dict[int, dict[str, Any]],
    mapping: dict[str, Any],
) -> dict[str, Any]:
    encoded = encode_v15(candidate)
    if decode_v15(encoded) != candidate:
        raise RuntimeError("v15 encode/decode round trip changed the 84/7 candidate")

    kind_counts = Counter(component.kind for component in candidate.components)
    if kind_counts[30]:
        raise RuntimeError("illegal native com_add kind 30 appears in the candidate")
    reviewed_gate = (
        kind_counts[4]
        + kind_counts[6]
        + kind_counts[7]
        + kind_counts[9]
        + kind_counts[12] * 2
    )
    if reviewed_gate != EXPECTED_SCORE["gate"] or candidate.energy != EXPECTED_SCORE["energy"]:
        raise RuntimeError(
            f"physical cost mismatch: gate={reviewed_gate}, energy={candidate.energy}"
        )
    if kind_counts[12] != 12:
        raise RuntimeError(f"physical Switch count changed: {kind_counts[12]}")

    connectivity = analyze_connectivity(candidate)
    for field in (
        "unsupported_component_kind_counts",
        "unconnected_pin_count",
        "multi_driver_network_count",
        "undriven_network_count",
        "sinkless_network_count",
        "width_mismatch_network_count",
        "cycle_component_count",
    ):
        if connectivity[field]:
            raise RuntimeError(f"candidate connectivity failure {field}: {connectivity[field]!r}")
    geometry = audit_sprite_geometry(candidate, DEFAULT_COMPONENT_SPRITE_ROOT)
    if (
        geometry.unsupported_component_kinds
        or geometry.component_overlap_cells
        or geometry.wire_collisions
        or geometry.wire_interior_pin_contacts
    ):
        raise RuntimeError(f"candidate sprite geometry failure: {geometry!r}")

    resolved = physical._audit_resolved_networks(
        candidate.components,
        candidate.wires,
        connections,
        expected_tri_state_output_count=12,
    )
    resolved["adversarial_foreign_label_rejected"] = physical._self_test_resolved_network_guard(
        candidate.components,
        candidate.wires,
        connections,
        expected_tri_state_output_count=12,
    )

    logical = _logical_states(tuple(payload["factory_dag"]["nodes"]))
    proxy = physical._proxy_for_semantics(candidate)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_PROXY.write_bytes(encode_v15(proxy))
    engine = physical._load_engine()
    engine.CIRCUIT_PATH = OUT_PROXY
    evaluated, compiled, networks, _component_outputs = engine.evaluate()
    if len(evaluated.components) != len(candidate.components):
        raise RuntimeError("semantic proxy changed the physical component population")

    label_index = mapping["label_index"]
    node_pin_refs = dict(mapping["node_pin_refs"])
    cin_node = next(
        node_id for node_id, node in by_id.items() if node["op"] == "INPUT" and node["label"] == "cin"
    )
    node_pin_refs[cin_node] = (label_index["Carry in"], "in")
    node_networks: dict[int, int] = {}
    node_replay_mismatches = []
    for node_id, state in logical.items():
        component_index, pin_name = node_pin_refs[node_id]
        key = (component_index, pin_name)
        if key not in compiled.pin_network:
            raise RuntimeError(f"node {node_id} output pin is physically disconnected: {key!r}")
        network = compiled.pin_network[key]
        signal = networks[network]
        node_networks[node_id] = network
        mismatched = []
        if signal.bits[0] != state["bits"]:
            mismatched.append("bits")
        if signal.driven != state["driven"]:
            mismatched.append("driven")
        if signal.conflict != state["conflict"]:
            mismatched.append("conflict")
        if signal.depth != state["depth"]:
            mismatched.append("depth")
        if mismatched:
            node_replay_mismatches.append({"node": node_id, "fields": mismatched})
    if node_replay_mismatches:
        raise RuntimeError(f"physical node replay mismatch: {node_replay_mismatches[:4]!r}")

    bus_stats = []
    seen_bus_networks = set()
    for node_id, node in by_id.items():
        if node["op"] != "BUS":
            continue
        switches = mapping["bus_switches"][node_id]
        networks_for_outputs = {
            compiled.pin_network[(switch, "out")] for switch in switches
        }
        if len(networks_for_outputs) != 1:
            raise RuntimeError(f"BUS {node_id} Switch outputs are physically partitioned")
        network = next(iter(networks_for_outputs))
        if network in seen_bus_networks:
            raise RuntimeError(f"BUS {node_id} aliases another resolved network")
        seen_bus_networks.add(network)
        pins = compiled.network_pins[network]
        tri_drivers = [pin for pin in pins if pin.direction == T]
        ordinary_drivers = [pin for pin in pins if pin.direction == O]
        if len(tri_drivers) != 2 or ordinary_drivers:
            raise RuntimeError(
                f"BUS {node_id} driver set changed: T={len(tri_drivers)}, O={len(ordinary_drivers)}"
            )
        signal = networks[network]
        bus_stats.append(
            {
                "node": node_id,
                "physical_network": network,
                "tri_state_driver_count": len(tri_drivers),
                "arrival": signal.depth,
                "z_assignment_count": ((~signal.driven) & ALL).bit_count(),
                "conflict_assignment_count": signal.conflict.bit_count(),
            }
        )
    if len(bus_stats) != 6 or any(item["conflict_assignment_count"] for item in bus_stats):
        raise RuntimeError(f"physical BUS audit failed: {bus_stats!r}")

    merger = mapping["merger"]
    output_nodes = tuple(int(value) for value in payload["factory_dag"]["outputs"])
    input_arrivals = []
    for bit, node_id in enumerate(output_nodes[:8]):
        network = compiled.pin_network[(merger, f"in{bit}")]
        signal = networks[network]
        if signal.bits[0] != logical[node_id]["bits"] or signal.driven != ALL:
            raise RuntimeError(f"sum input bit {bit} is not the reviewed driven signal")
        input_arrivals.append(signal.depth)
    carry_sink = label_index["Carry out"]
    carry_network = compiled.pin_network[(carry_sink, "out")]
    carry_signal = networks[carry_network]
    input_arrivals.append(carry_signal.depth)
    if input_arrivals != payload["metrics"]["output_arrivals"]:
        raise RuntimeError(
            f"physical output arrivals differ: {input_arrivals!r}"
        )

    sum_sink = label_index["Output"]
    sum_signal = networks[compiled.pin_network[(sum_sink, "out")]]
    variables = tuple(_variable(index) for index in range(17))
    carry = variables[16]
    expected_sum = []
    for left, right in zip(variables[:8], variables[8:16]):
        propagate = left ^ right
        expected_sum.append(propagate ^ carry)
        carry = (left & right) | (propagate & carry)
    if sum_signal.bits[:8] != tuple(expected_sum) or carry_signal.bits[0] != carry:
        raise RuntimeError("physical 84/7 candidate fails complete Byte Adder truth table")
    if sum_signal.driven != ALL or carry_signal.driven != ALL:
        raise RuntimeError("a primary output is high-impedance")
    packed_conflicts = sum(signal.conflict.bit_count() for signal in networks.values())
    if packed_conflicts:
        raise RuntimeError(f"physical candidate has {packed_conflicts} packed conflicts")
    global_depth = max(signal.depth for signal in networks.values())
    if global_depth != EXPECTED_SCORE["delay"] or sum_signal.depth != 7 or carry_signal.depth != 7:
        raise RuntimeError(
            f"physical recursive delay mismatch: global/sum/carry={global_depth}/{sum_signal.depth}/{carry_signal.depth}"
        )

    return {
        "candidate_bytes": encoded,
        "candidate_sha256": sha256(encoded).hexdigest(),
        "component_count": len(candidate.components),
        "wire_count": len(candidate.wires),
        "component_kind_counts": {str(key): value for key, value in sorted(kind_counts.items())},
        "reviewed_gate": reviewed_gate,
        "native_com_add_count": kind_counts[30],
        "connectivity": {
            "unconnected_pin_count": connectivity["unconnected_pin_count"],
            "unsafe_multi_driver_network_count": connectivity["multi_driver_network_count"],
            "undriven_network_count": connectivity["undriven_network_count"],
            "sinkless_network_count": connectivity["sinkless_network_count"],
            "width_mismatch_network_count": connectivity["width_mismatch_network_count"],
            "cycle_component_count": connectivity["cycle_component_count"],
            "topology_only_unit_depth": connectivity["unit_logic_depth"],
            "topology_depth_note": (
                "non-Z-aware graph depth; node-by-node tri-state semantic depth is authoritative"
            ),
        },
        "geometry": {
            "unsupported_component_kinds": list(geometry.unsupported_component_kinds),
            "component_overlap_cells": len(geometry.component_overlap_cells),
            "wire_collisions": len(geometry.wire_collisions),
            "wire_interior_pin_contacts": len(geometry.wire_interior_pin_contacts),
        },
        "resolved_networks": resolved,
        "semantic": {
            "vectors_checked": ASSIGNMENTS,
            "node_replay_count": len(logical),
            "node_replay_mismatch_count": len(node_replay_mismatches),
            "bus_nodes": bus_stats,
            "packed_conflict_cases": packed_conflicts,
            "output_arrivals": input_arrivals,
            "global_depth": global_depth,
            "sum_depth": sum_signal.depth,
            "carry_depth": carry_signal.depth,
            "sum_correct": True,
            "carry_correct": True,
        },
        "v15_round_trip_verified": True,
    }


def build_audit_deploy() -> dict[str, Any]:
    payload, by_id, source_review = _review_dag()
    candidate, connections, mapping = _build_physical(payload, by_id)
    audit = _audit_candidate(candidate, connections, payload, by_id, mapping)
    encoded = audit.pop("candidate_bytes")

    REPOSITORY_CANDIDATE.parent.mkdir(parents=True, exist_ok=True)
    REPOSITORY_CANDIDATE.write_bytes(encoded)
    if decode_v15(REPOSITORY_CANDIDATE.read_bytes()) != candidate:
        raise RuntimeError("repository candidate changed after direct write")

    _assert_game_not_running()
    if not FORMAL_SAVE.parent.is_dir():
        raise RuntimeError(f"formal byte_adder save directory is missing: {FORMAL_SAVE.parent}")
    FORMAL_SAVE.write_bytes(encoded)
    _assert_game_not_running()
    formal_bytes = FORMAL_SAVE.read_bytes()
    if formal_bytes != encoded or decode_v15(formal_bytes) != candidate:
        raise RuntimeError("formal save differs after direct replacement")

    certificate = {
        "schema": "turing-complete-byte-adder-hybrid84-physical-v1",
        "date": "2026-08-03",
        "source_review": source_review,
        "serialized_score": EXPECTED_SCORE,
        **audit,
        "repository_candidate": str(REPOSITORY_CANDIDATE.relative_to(ROOT)).replace("\\", "/"),
        "repository_candidate_matches": True,
        "formal_save": str(FORMAL_SAVE).replace("\\", "/"),
        "formal_save_matches": True,
        "backup_created": False,
        "game_started": False,
    }
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_CERTIFICATE.write_text(
        json.dumps(certificate, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(json.dumps(certificate, ensure_ascii=False, indent=2))
    return certificate


if __name__ == "__main__":
    build_audit_deploy()
