"""穷举 K/P/G 三态的二位编码与一层组合表达式。

高位状态与低位状态的组合规则是：高位为 P 时取低位，否则取高位。本脚本在
全部 24 种注入编码上枚举一层普通门和冲突安全的 Switch BUS，报告编码、初始
A/B 生成、状态组合及 Cin 求值的最低成本。
"""

from __future__ import annotations

from dataclasses import dataclass
from itertools import permutations, product
import json
from pathlib import Path


STATES = ("K", "P", "G")
CODES = ((0, 0), (0, 1), (1, 0), (1, 1))
OUTPUT = Path(__file__).with_name("transition_encoding_frontier.json")


@dataclass(frozen=True)
class Formula:
    values: tuple[int, ...]
    gate: int
    text: str
    kind: str


def primitive_formulas(rows: tuple[tuple[int, ...], ...], names: tuple[str, ...]) -> list[Formula]:
    atoms = [(name, tuple(row[index] for row in rows)) for index, name in enumerate(names)]
    atoms.extend((("0", (0,) * len(rows)), ("1", (1,) * len(rows))))
    result = [Formula(values, 0, name, "wire") for name, values in atoms]
    for name, values in atoms:
        result.append(Formula(tuple(1 - value for value in values), 1, f"NOT({name})", "NOT"))
    operations = {
        "AND": lambda left, right: left & right,
        "OR": lambda left, right: left | right,
        "NAND": lambda left, right: 1 - (left & right),
        "NOR": lambda left, right: 1 - (left | right),
    }
    for left_index, (left_name, left_values) in enumerate(atoms):
        for right_name, right_values in atoms[left_index:]:
            for op_name, operation in operations.items():
                result.append(
                    Formula(
                        tuple(operation(left, right) for left, right in zip(left_values, right_values)),
                        1,
                        f"{op_name}({left_name},{right_name})",
                        op_name,
                    )
                )

    drivers = [(enable_name, data_name, enable, data) for enable_name, enable in atoms for data_name, data in atoms]
    for count in (1, 2, 3):
        # Repetition and ordering cannot improve a wired BUS, so combinations
        # with replacement are generated by monotone driver indices.
        def visit(start: int, selected: list[int]) -> None:
            if len(selected) == count:
                values: list[int] = []
                for row_index in range(len(rows)):
                    active = [
                        drivers[index][3][row_index]
                        for index in selected
                        if drivers[index][2][row_index]
                    ]
                    if active and any(value != active[0] for value in active[1:]):
                        return
                    values.append(active[0] if active else 0)
                text = "BUS(" + ",".join(
                    f"SW({drivers[index][0]},{drivers[index][1]})" for index in selected
                ) + ")"
                result.append(Formula(tuple(values), 2 * count, text, f"switch{count}"))
                return
            for index in range(start, len(drivers)):
                selected.append(index)
                visit(index + 1, selected)
                selected.pop()

        visit(0, [])

    best: dict[tuple[int, ...], Formula] = {}
    for formula in result:
        old = best.get(formula.values)
        if old is None or (formula.gate, len(formula.text)) < (old.gate, len(old.text)):
            best[formula.values] = formula
    return list(best.values())


def best_match(formulas: list[Formula], target: tuple[int, ...]) -> Formula | None:
    matches = [formula for formula in formulas if formula.values == target]
    return min(matches, key=lambda formula: (formula.gate, len(formula.text))) if matches else None


def state_compose(high: str, low: str) -> str:
    return low if high == "P" else high


def main() -> None:
    records = []
    for assigned in permutations(CODES, 3):
        encoding = dict(zip(STATES, assigned))

        init_rows = tuple((a, b) for a, b in product((0, 1), repeat=2))
        init_states = tuple("K" if (a, b) == (0, 0) else "G" if (a, b) == (1, 1) else "P" for a, b in init_rows)
        init_formulas = primitive_formulas(init_rows, ("a", "b"))
        init_bits = [
            best_match(init_formulas, tuple(encoding[state][bit] for state in init_states))
            for bit in range(2)
        ]

        combine_state_rows = tuple(product(STATES, repeat=2))
        combine_rows = tuple(
            encoding[high] + encoding[low] for high, low in combine_state_rows
        )
        combine_formulas = primitive_formulas(combine_rows, ("h0", "h1", "l0", "l1"))
        combined_states = tuple(state_compose(high, low) for high, low in combine_state_rows)
        combine_bits = [
            best_match(combine_formulas, tuple(encoding[state][bit] for state in combined_states))
            for bit in range(2)
        ]

        carry_rows = tuple(encoding[state] + (cin,) for state, cin in product(STATES, (0, 1)))
        carry_target = tuple(
            0 if state == "K" else 1 if state == "G" else cin
            for state, cin in product(STATES, (0, 1))
        )
        carry_formula = best_match(
            primitive_formulas(carry_rows, ("x0", "x1", "cin")),
            carry_target,
        )

        if any(formula is None for formula in (*init_bits, *combine_bits, carry_formula)):
            continue
        assert carry_formula is not None
        record = {
            "encoding": {state: list(encoding[state]) for state in STATES},
            "initial": [formula.__dict__ for formula in init_bits if formula is not None],
            "combine": [formula.__dict__ for formula in combine_bits if formula is not None],
            "carry": carry_formula.__dict__,
            "cost": {
                "initial": sum(formula.gate for formula in init_bits if formula is not None),
                "combine": sum(formula.gate for formula in combine_bits if formula is not None),
                "carry": carry_formula.gate,
            },
        }
        records.append(record)

    records.sort(
        key=lambda item: (
            item["cost"]["combine"],
            item["cost"]["initial"],
            item["cost"]["carry"],
        )
    )
    OUTPUT.write_text(
        json.dumps(
            {
                "schema": "byte-adder-transition-encoding-frontier-v1",
                "encoding_count": len(records),
                "records": records,
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    for item in records[:12]:
        print(item["encoding"], item["cost"])
        print("  init", [formula["text"] for formula in item["initial"]])
        print("  comb", [formula["text"] for formula in item["combine"]])
        print("  carry", item["carry"]["text"])


if __name__ == "__main__":
    main()
